### ISSUE TITLE
Some possible LR data api tweaks.

### ISSUE THREAD

**Issue by skwlilac** [OrdnanceSurvey/os-data-hub-tutorials#1]
A couple of things FYI:

1. the API framework used on the landregistry linked data site, [elda](https://github/com/epimorphics/elda), provides an `_pageSize` parameter which in this case can be increased upto 200 (a configured maximum). There is some info about the configuration of all the api endpoints [here](https://landregistry.data.gov.uk/api-config).
2. You can also use the views (`_view=`) and properties (`_properties=` ) parameters to tune the data in the response up or down from the defaults e.g.<br/> `?_pageSize=200&_view=basic&_properties=transactionId,transactionDate,pricePaid,propertyAddress.postcode` <br/>will return just the data that the application appears to be using - will reduce the payload size and avoid having to prune away the data its not interested in.

Great to see someone making good use of this API.

**Comment by steve-kingston** [comment]
Hi @skwlilac, thanks very much for the pointers. Those changes will definitely help improve the workflow in the tutorial.

I'll look to implement these.

Thanks,
Steve

**Comment by steve-kingston** [comment]
Incorporated suggested changes via 3087ecc
